# Generated by Django 3.2.9 on 2021-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('surname', models.CharField(max_length=512)),
                ('avg_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
            ],
        ),
    ]
